<?php
require_once __DIR__.'/../includes/bootstrap.php';require_auth();
$u=current_user($pdo);$uid=(int)$u['id'];$teamId=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);
$stmt=$pdo->prepare("SELECT t.*,tm.role membership_role FROM teams t JOIN team_members tm ON tm.team_id=t.id WHERE t.id=? AND tm.user_id=?");$stmt->execute([$teamId,$uid]);$team=$stmt->fetch();
if(!$team){flash('error','Team not found.');redirect('/teams/index.php');}
$_SESSION['team_id']=(int)$team['id'];
$stmt=$pdo->prepare("SELECT u.id,u.name,u.email,tm.role,(SELECT COUNT(*) FROM tasks WHERE assigned_to=u.id AND team_id=?) task_count FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=? ORDER BY FIELD(tm.role,'admin','manager','member'),u.name");$stmt->execute([$teamId,$teamId]);$members=$stmt->fetchAll();
$stmt=$pdo->prepare("SELECT status,COUNT(*) c FROM tasks WHERE team_id=? GROUP BY status");$stmt->execute([$teamId]);$stats=['todo'=>0,'in_progress'=>0,'completed'=>0];foreach($stmt->fetchAll() as $r)$stats[$r['status']]=(int)$r['c'];
$stmt=$pdo->prepare("SELECT * FROM team_invitations WHERE team_id=? AND status='pending' ORDER BY id DESC");$stmt->execute([$teamId]);$invites=$stmt->fetchAll();
$pageTitle=$team['name'];$activePage='teams';require __DIR__.'/../includes/header.php';
?>
<section class="hero-row"><div><p class="eyebrow">TEAM WORKSPACE</p><h2><?=e($team['name'])?></h2><p><?=e($team['description']?:'Manage members and shared workload.')?></p></div><div class="hero-actions"><?php if($team['membership_role']==='admin'):?><a class="btn btn-secondary" href="teams/edit.php?id=<?=$teamId?>">Edit Team</a><?php endif;?><?php if(in_array($team['membership_role'],['admin','manager'],true)):?><a class="btn btn-primary" href="teams/invite.php?id=<?=$teamId?>">＋ Invite Member</a><?php endif;?></div></section>
<section class="stats-grid"><article class="stat-card"><span class="stat-dot blue"></span><div><small>Members</small><strong><?=count($members)?></strong></div></article><article class="stat-card"><span class="stat-dot gray"></span><div><small>To Do</small><strong><?=$stats['todo']?></strong></div></article><article class="stat-card"><span class="stat-dot cyan"></span><div><small>In Progress</small><strong><?=$stats['in_progress']?></strong></div></article><article class="stat-card"><span class="stat-dot green"></span><div><small>Completed</small><strong><?=$stats['completed']?></strong></div></article></section>
<section class="dashboard-grid"><article class="panel table-wrap"><div class="panel-head"><h3>Members</h3></div><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Assigned tasks</th></tr></thead><tbody><?php foreach($members as $m):?><tr><td><?=e($m['name'])?></td><td><?=e($m['email'])?></td><td><span class="badge status-in_progress"><?=e(ucfirst($m['role']))?></span></td><td><?=$m['task_count']?></td></tr><?php endforeach;?></tbody></table></article>
<article class="panel"><div class="panel-head"><h3>Pending Invitations</h3></div><div class="invitation-list"><?php foreach($invites as $i):?><div><strong><?=e($i['email'])?></strong><small><?=e(ucfirst($i['role']))?> · expires <?=e(date('M d',strtotime($i['expires_at'])))?></small></div><?php endforeach;?><?php if(!$invites):?><p class="muted">No pending invitations.</p><?php endif;?></div></article></section>
<?php require __DIR__.'/../includes/footer.php';?>